package telemetry

import "github.com/prometheus/client_golang/prometheus"

// Metrics bundles Prometheus instruments used by API and workers.
type Metrics struct {
	ScanRunsTotal     prometheus.Counter
	ScanDurationMS    prometheus.Histogram
	FindingsGenerated prometheus.Counter
}

// NewMetrics initializes a dedicated registry-safe instrument set.
func NewMetrics() *Metrics {
	return &Metrics{
		ScanRunsTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "accessloom",
			Subsystem: "scan",
			Name:      "runs_total",
			Help:      "Total number of scan runs.",
		}),
		ScanDurationMS: prometheus.NewHistogram(prometheus.HistogramOpts{
			Namespace: "accessloom",
			Subsystem: "scan",
			Name:      "duration_milliseconds",
			Help:      "Duration of scans in milliseconds.",
			Buckets:   []float64{100, 250, 500, 1000, 2000, 5000, 10000},
		}),
		FindingsGenerated: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "accessloom",
			Subsystem: "analysis",
			Name:      "findings_generated_total",
			Help:      "Number of findings generated by the risk engine.",
		}),
	}
}
