package telemetry

import "github.com/prometheus/client_golang/prometheus"

// Metrics bundles Prometheus instruments used by API and workers.
type Metrics struct {
	ScanRunsTotal                          prometheus.Counter
	ScanSuccessTotal                       prometheus.Counter
	ScanFailureTotal                       prometheus.Counter
	ScanPartialTotal                       prometheus.Counter
	ScanInFlight                           prometheus.Gauge
	ScanDurationMS                         prometheus.Histogram
	FindingsGenerated                      prometheus.Counter
	RepoScanRunsTotal                      prometheus.Counter
	RepoScanFailureTotal                   prometheus.Counter
	RepoScanDurationMS                     prometheus.Histogram
	AuthzPolicyShadowEvaluationsTotal      prometheus.Counter
	AuthzPolicyShadowDivergencesTotal      prometheus.Counter
	AuthzPolicyShadowEvaluationErrorsTotal prometheus.Counter
}

// NewMetrics initializes a dedicated registry-safe instrument set.
func NewMetrics() *Metrics {
	return &Metrics{
		ScanRunsTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "scan",
			Name:      "runs_total",
			Help:      "Total number of scan runs.",
		}),
		ScanSuccessTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "scan",
			Name:      "success_total",
			Help:      "Total number of successful scan runs.",
		}),
		ScanFailureTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "scan",
			Name:      "failure_total",
			Help:      "Total number of failed scan run attempts.",
		}),
		ScanPartialTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "scan",
			Name:      "partial_total",
			Help:      "Total number of scans completed with partial source errors.",
		}),
		ScanInFlight: prometheus.NewGauge(prometheus.GaugeOpts{
			Namespace: "identrail",
			Subsystem: "scan",
			Name:      "in_flight",
			Help:      "Current number of in-flight scan triggers.",
		}),
		ScanDurationMS: prometheus.NewHistogram(prometheus.HistogramOpts{
			Namespace: "identrail",
			Subsystem: "scan",
			Name:      "duration_milliseconds",
			Help:      "Duration of scans in milliseconds.",
			Buckets:   []float64{100, 250, 500, 1000, 2000, 5000, 10000},
		}),
		FindingsGenerated: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "analysis",
			Name:      "findings_generated_total",
			Help:      "Number of findings generated by the risk engine.",
		}),
		RepoScanRunsTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "repo_scan",
			Name:      "runs_total",
			Help:      "Total number of repository exposure scans.",
		}),
		RepoScanFailureTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "repo_scan",
			Name:      "failure_total",
			Help:      "Total number of failed repository exposure scans.",
		}),
		RepoScanDurationMS: prometheus.NewHistogram(prometheus.HistogramOpts{
			Namespace: "identrail",
			Subsystem: "repo_scan",
			Name:      "duration_milliseconds",
			Help:      "Duration of repository exposure scans in milliseconds.",
			Buckets:   []float64{100, 250, 500, 1000, 2000, 5000, 10000, 30000, 60000},
		}),
		AuthzPolicyShadowEvaluationsTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "authz_policy_rollout",
			Name:      "shadow_evaluations_total",
			Help:      "Total number of shadow candidate policy evaluations.",
		}),
		AuthzPolicyShadowDivergencesTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "authz_policy_rollout",
			Name:      "shadow_divergences_total",
			Help:      "Total number of shadow evaluations where candidate decision diverged from enforced decision.",
		}),
		AuthzPolicyShadowEvaluationErrorsTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "authz_policy_rollout",
			Name:      "shadow_evaluation_errors_total",
			Help:      "Total number of shadow candidate evaluations that failed.",
		}),
	}
}
