name: OSV Scanner

on:
  pull_request:
  schedule:
    - cron: '31 2 * * *'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  osv-pr:
    if: github.event_name == 'pull_request'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@375a0e8ebdc98e99b02ac4338a724f5750f21213
    with:
      scan-args: |-
        --recursive
        .

  osv-default:
    if: github.event_name != 'pull_request'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@375a0e8ebdc98e99b02ac4338a724f5750f21213
    with:
      scan-args: |-
        --recursive
        .
