export const PRERENDER_ROUTES = [
  '/',
  '/product',
  '/features',
  '/features/aws',
  '/features/kubernetes',
  '/features/git-scanner',
  '/features/trust-graph',
  '/solutions',
  '/solutions/aws',
  '/solutions/kubernetes',
  '/solutions/multi-cloud',
  '/solutions/platform-engineering',
  '/solutions/security-teams',
  '/pricing',
  '/demo',
  '/docs',
  '/blog',
  '/security',
  '/about',
  '/enterprise',
  '/privacy',
  '/terms',
  '/privacy-choices'
] as const;
